### ISSUE TITLE
Random hangs when starting the game

### ISSUE THREAD

**Issue by mineland-0066** [alphaqu/DashLoader#26]
i normally use this mod with my pack of vanilla friendly mods, and at random times when starting the game it will just not start, and i know it is dashloader because the console constantly outputs a `[STDOUT]: Waiting for dash` message every second.

this doesnt always happen and its at very random times. dunno what could it be.
[logs.txt](https://github.com/alphaqu/DashLoader/files/6562666/logs.txt)

**Comment by alphaqu** [comment]
Please try on 1.4.5 and see if it fixes the issue.

**Comment by mineland-0066** [comment]
it made it worse, now i had to remove the mod "hydrogen" because it conflicted with dash, and another error occourred
[log.txt](https://github.com/alphaqu/DashLoader/files/6598711/log.txt)
at least it now does something, but it basically is another error instead so i gue
ss its """"resolved"""?

[modlist.txt](https://github.com/alphaqu/DashLoader/files/6598757/modlist.txt)
idk, here is my mod list if needed

**Comment by alphaqu** [comment]
Hydrogen was never compatible, You also need to send me the entire logs after the caching has been completed.
